### ISSUE TITLE
Exportar informações do container do banco de dados

### ISSUE THREAD

**Issue by victorffernandes** [victorffernandes/smart-attendance-bff#3]
Configurar para exportar para fora do container as informações gravadas nele, para tornar o banco containerizado realmente "persistente"
```
services:
  db:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=smartdb
      - MYSQL_USER=mysql_user
      - MYSQL_PASSWORD=priv4te
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3306:3306"
```
